%
% MackeyGlass_dde23.m
%
% MATLAB vector field function for: MackeyGlass
%
% This file was generated by the program VFGEN (Version:2.1.0)
% Generated on  3-Jun-2007 at 12:24
%
%
% The lags are: {tau}
%
function vf = MackeyGlass_dde23(t,x,Zlags,p)
    % State variables
    x          = x(1);
    % Parameters
    a          = p(1);
    b          = p(2);
    tau        = p(3);
    ep         = p(4);
    
    
    delayedx = Zlags(1,1);
    vf = zeros(1,1);
    vf(1) = -b*x+delayedx*a*(1+delayedx^ep)^(-1);